"""Add created_at and updated_at to practitioners

Revision ID: 17395bf764f3
Revises: 80185fbfcd64
Create Date: 2025-05-27 00:48:06.113089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17395bf764f3'
down_revision: Union[str, None] = '80185fbfcd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioners', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('practitioners', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practitioners', 'updated_at')
    op.drop_column('practitioners', 'created_at')
    # ### end Alembic commands ###
