"""initial

Revision ID: 80185fbfcd64
Revises: 
Create Date: 2025-05-25 09:49:16.090026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80185fbfcd64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.JSON(), nullable=True),
    sa.Column('telecom', sa.JSON(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('part_of', sa.JSON(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('endpoint', sa.JSON(), nullable=True),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=True),
    sa.Column('telecom', sa.JSON(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('insurance_company', sa.String(), nullable=True),
    sa.Column('insurance_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('stock_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity_changed', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_audit_logs_id'), 'stock_audit_logs', ['id'], unique=False)
    op.create_table('medication_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('medication_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('authored_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_requests_id'), 'medication_requests', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('identifier', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('code_system', sa.String(), nullable=False),
    sa.Column('code_value', sa.String(), nullable=False),
    sa.Column('code_display', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.JSON(), nullable=True),
    sa.Column('form', sa.JSON(), nullable=True),
    sa.Column('amount', sa.JSON(), nullable=True),
    sa.Column('ingredient', sa.JSON(), nullable=True),
    sa.Column('batch', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('practitioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('telecom', sa.JSON(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.JSON(), nullable=True),
    sa.Column('qualification', sa.JSON(), nullable=True),
    sa.Column('communication', sa.JSON(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token_expires', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioners_email'), 'practitioners', ['email'], unique=True)
    op.create_index(op.f('ix_practitioners_username'), 'practitioners', ['username'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('item', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.JSON(), nullable=True),
    sa.Column('parameter', sa.JSON(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('code', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.JSON(), nullable=False),
    sa.Column('characteristic', sa.JSON(), nullable=True),
    sa.Column('instance', sa.JSON(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('fhir_medication_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fhir_medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.JSON(), nullable=False),
    sa.Column('encounter', sa.JSON(), nullable=True),
    sa.Column('authored_on', sa.DateTime(), nullable=False),
    sa.Column('requester', sa.JSON(), nullable=False),
    sa.Column('reason_code', sa.JSON(), nullable=True),
    sa.Column('dosage_instruction', sa.JSON(), nullable=False),
    sa.Column('dispense_request', sa.JSON(), nullable=True),
    sa.Column('substitution', sa.JSON(), nullable=True),
    sa.Column('prescription_source', sa.Enum('ELECTRONIC', 'SCANNED', 'MANUAL', name='prescriptionsource'), nullable=False),
    sa.Column('prescription_status', sa.Enum('PENDING', 'VERIFIED', 'DISPENSED', 'CANCELLED', 'EXPIRED', name='prescriptionstatus'), nullable=False),
    sa.Column('scanned_image_url', sa.String(length=255), nullable=True),
    sa.Column('ocr_text', sa.String(length=1000), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('verification_notes', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescriber_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescriber_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('item', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.JSON(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('quantity_received', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_table('medication_dispenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PREPARATION', 'IN_PROGRESS', 'CANCELLED', 'ON_HOLD', 'COMPLETED', 'ENTERED_IN_ERROR', 'STOPPED', 'DECLINED', 'UNKNOWN', name='dispensestatus'), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dispenser_id', sa.Integer(), nullable=True),
    sa.Column('prescriber_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('when_prepared', sa.DateTime(), nullable=True),
    sa.Column('when_handed_over', sa.DateTime(), nullable=True),
    sa.Column('dosage_instruction', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('was_substituted', sa.Boolean(), nullable=True),
    sa.Column('substitution_reason', sa.String(), nullable=True),
    sa.Column('substitution_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispenser_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescriber_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('charge_item', sa.JSON(), nullable=True),
    sa.Column('price_component', sa.JSON(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_table('medication_dispenses')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_practitioners_username'), table_name='practitioners')
    op.drop_index(op.f('ix_practitioners_email'), table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medication_requests_id'), table_name='medication_requests')
    op.drop_table('medication_requests')
    op.drop_index(op.f('ix_stock_audit_logs_id'), table_name='stock_audit_logs')
    op.drop_table('stock_audit_logs')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
